#!/usr/bin/env python3
"""
Generate partitions.csv for ESP32 PhotoFrame based on sdkconfig settings.

Reads CONFIG_USE_INTERNAL_FLASH_STORAGE and CONFIG_ESPTOOLPY_FLASHSIZE_*
from one or more config files to determine the appropriate partition layout.

Usage:
    python3 gen_partitions.py --sdkconfig sdkconfig.defaults boards/sdkconfig.defaults.board --output partitions.csv
"""

import argparse
import sys

FLASH_SIZE_MAP = {
    "CONFIG_ESPTOOLPY_FLASHSIZE_8MB=y": 8,
    "CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y": 16,
    "CONFIG_ESPTOOLPY_FLASHSIZE_32MB=y": 32,
    "CONFIG_ESPTOOLPY_FLASHSIZE_64MB=y": 64,
    "CONFIG_ESPTOOLPY_FLASHSIZE_128MB=y": 128,
}

HEADER = """\
# Generated by scripts/gen_partitions.py - do not edit manually
# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x6000,
otadata,  data, ota,     0xf000,  0x2000,
phy_init, data, phy,     0x11000, 0x1000,
"""


def parse_config_files(paths):
    use_internal_flash = False
    flash_size_mb = 16  # default

    for path in paths:
        try:
            with open(path) as f:
                for line in f:
                    line = line.strip()
                    if line == "CONFIG_USE_INTERNAL_FLASH_STORAGE=y":
                        use_internal_flash = True
                    elif line in FLASH_SIZE_MAP:
                        flash_size_mb = FLASH_SIZE_MAP[line]
        except FileNotFoundError:
            print(f"Warning: config file not found: {path}", file=sys.stderr)

    return use_internal_flash, flash_size_mb


def generate_csv(use_internal_flash, flash_size_mb):
    csv = HEADER

    if use_internal_flash:
        if flash_size_mb == 8:
            stg_size = 8 * 1024 * 1024 - 0x520000
            csv += (
                f"ota_0,    app,  ota_0,   0x20000,  0x280000,\n"
                f"ota_1,    app,  ota_1,   0x2A0000, 0x280000,\n"
                f"storage,  data, littlefs,0x520000, {stg_size:#010x},\n"
            )
        else:
            stg_size = (flash_size_mb - 8) * 1024 * 1024
            csv += (
                f"ota_0,    app,  ota_0,   0x20000,  0x380000,\n"
                f"ota_1,    app,  ota_1,   0x3A0000, 0x380000,\n"
                f"storage,  data, littlefs,0x720000, {stg_size:#010x},\n"
            )
        print(
            f"Partition table: internal flash storage enabled "
            f"({flash_size_mb}MB flash, storage size: {stg_size:#010x})",
            file=sys.stderr,
        )
    else:
        # OTA size scales with flash: 0x78000 per MB (gives 0x780000 for 16MB).
        ota_size = flash_size_mb * 0x78000
        ota_1_offset = 0x20000 + ota_size
        csv += (
            f"ota_0,    app,  ota_0,   0x20000,  {ota_size:#010x},\n"
            f"ota_1,    app,  ota_1,   {ota_1_offset:#010x},{ota_size:#010x},\n"
        )
        print(
            f"Partition table: no internal flash storage "
            f"({flash_size_mb}MB flash, OTA size: {ota_size:#010x})",
            file=sys.stderr,
        )

    return csv


def main():
    parser = argparse.ArgumentParser(
        description="Generate partitions.csv for ESP32 PhotoFrame"
    )
    parser.add_argument(
        "--sdkconfig",
        nargs="+",
        required=True,
        help="One or more sdkconfig/defaults files to read",
    )
    parser.add_argument("--output", required=True, help="Path to write partitions.csv")
    args = parser.parse_args()

    use_internal_flash, flash_size_mb = parse_config_files(args.sdkconfig)
    csv = generate_csv(use_internal_flash, flash_size_mb)

    with open(args.output, "w") as f:
        f.write(csv)

    return 0


if __name__ == "__main__":
    sys.exit(main())
